### PR TITLE
Detect and handle errors fetching the latest version

### LINKED ISSUE #59: Unclear failure mode with "undefined" version
I'm not completely sure what failed, however ~one~ ~a couple~ a few of our CI runs ~just~ failed on this action with:
> Installing DVC from: https://dvc.org/download/linux-deb/dvc-undefined
> DVC Download Failed, trying from GitHub Releases
> Installing DVC from: https://github.com/iterative/dvc/releases/download/undefined/dvc_undefined_amd64.deb

A retry of the same run shortly afterwards succeeded.

My guess is that the logic to determine the version number failed, however did so in a manner which wasn't immediately an error. Perhaps if the version number lookup fails it should error immediately?

### PR DESCRIPTION
**Pull request by PeterJCLaw**
This attempts to detect such errors, assuming that they appear with suitable HTTP status codes, and raises useful errors for them.

It looks like CI testing covers the happy cases, unsure how to test the failing case.

Fixes https://github.com/iterative/setup-dvc/issues/59

### CODE REVIEW

**Comment by dacbd** [comment]
@0x2b3bfa0

**Comment by shcheklein** [comment]
@0x2b3bfa0 could you please review this? It looks good to me overall.

**Review by 0x2b3bfa0 — DISMISSED** [review]
Yes, sorry for the belated reply, looks awesome!

**Comment by shcheklein** [comment]
@0x2b3bfa0 is there a way to generate / regenerate index on CI ?

**Comment by 0x2b3bfa0** [comment]
Clever! 😄 

Yes, we don't generate it, but we check its integrity to prevent contributors from wreaking havoc:

https://github.com/iterative/setup-dvc/blob/d549770196ed130ba41697c4713281c349917d5e/.github/workflows/check.yml#L7-L14

**Comment by shcheklein** [comment]
> Yes, we don't generate it, but we check its integrity to prevent contributors from wreaking havoc:

I'm more worried about security in this case :)

**Comment by shcheklein** [comment]
```
           npm ci 
           npm run build 
           git diff --exit-code 
```

does it build it and check that we are getting the same result?

**Comment by 0x2b3bfa0** [comment]
> _I'm more worried about security in this case_

That's exactly what I mean. 😄 The excerpt I quoted above would fail if `index.js` didn't contain exactly what's supposed to.

**Comment by 0x2b3bfa0** [comment]
And, by the way, checks are broken. I'll have to fix them before merging.

**Comment by shcheklein** [comment]
> And, by the way, checks are broken. I'll have to fix them before merging.

I've reopened it to trigger the checks ... thanks for the fix!

**Review by 0x2b3bfa0 — APPROVED** [review]

**Comment by 0x2b3bfa0** [comment]
> _I've reopened it to trigger the checks ... thanks for the fix!_

Much better than what I did! 🤦🏼‍♂️

**Comment by PeterJCLaw** [comment]
For your build integrity checks, you might enjoy https://github.com/marketplace/actions/validate-generated-files.

**Comment by 0x2b3bfa0** [comment]
Thanks! `git diff --exit-code` is (almost) short and memorable enough, but your action looks great!

**Pull request merged**
